<a href="https://colab.research.google.com/github/parth5757/pyhon_project/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Hi Parth

In [1]:
import numpy as np

In [2]:
# myarr = np.array([3,6,32,7], np.int64) # For single use only it print 0, 1 = 3, 6
myarr = np.array([[3,6,32,7]], np.int64)

In [3]:
myarr[0, 1]

6

In [4]:
myarr.dtype

dtype('int64')

In [5]:
myarr[0,1] = 45

In [6]:
myarr

array([[ 3, 45, 32,  7]])

Array creation: Conversion from other python structure

In [7]:
listarray = np.array([[1,2,3], [5,8,5], [0,5,1]])

In [8]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 5, 1]])

In [9]:
listarray.dtype

dtype('int64')

In [10]:
 listarray.shape

(3, 3)

In [11]:
listarray.size

9

In [12]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [15]:
zeros = np.zeros((2,5))

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
rng = np.arange(15)

In [18]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
lspace = np.linspace(1,4,4)

In [22]:
lspace

array([1., 2., 3., 4.])

In [23]:
 emp = np.empty((4,6))

In [24]:
emp

array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

In [25]:
emp_like = np.empty_like(lspace)

In [26]:
emp_like

array([1., 2., 3., 4.])

In [27]:
ide = np.identity(45)

In [28]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [29]:
ide.shape

(45, 45)

In [30]:
arr = np.arange(99)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [33]:
arr = arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [35]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
arr.shape

(99,)

In [37]:
x = [[1,2,3], [4,5,6], [7,1,0]]

In [40]:
ar = np.array(x)

In [41]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])
at row side the 2d array have axis 0 and colum side is axis 1

In [43]:
ar.sum(axis=0)

array([12,  8,  9])

In [44]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [45]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

IT TRANSFER ROW INTO COLUMN AND COLUMN INTO ROW

In [46]:
ar.flat

In [48]:
for i in ar.flat:
  print(i)

1
2
3
4
5
6
7
1
0


In [49]:
ar.ndim

2

In [51]:
ar.size

9

In [52]:
ar.nbytes

72

to know total number of bytes

In [53]:
one = np.array([1,3,4,634,2])

In [54]:
one.argmax()

3

In [55]:
one.argmax()

3

In [56]:
one.argmin()

0

In [57]:
one.argsort()

array([0, 4, 1, 2, 3])

In [58]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [59]:
ar.argmin()

8

In [60]:
ar.argmax()

6

In [61]:
ar.argmax(axis=0)

array([2, 1, 1])

In [62]:
ar.argmax(axis=1)

array([2, 2, 0])

In [63]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [66]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [67]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [68]:
ar2 = np.array([[1,2,1],
                [4, 0, 6],
                [8, 1, 0]])

In [69]:
ar +ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [70]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [71]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [73]:
ar.sum()

29

In [74]:
ar.max()

7

In [75]:
ar.min()

0

In [77]:
# np.where(ar>5)
type(np.where(ar>5))

tuple

In [82]:
np.count_nonzero(ar)

8

In [83]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [84]:
ar[1,2]=0

In [85]:
import sys

In [86]:
py_ar = [0,4,55,2]

In [88]:
np_ar = np.array(py_ar)

In [89]:
sys.getsizeof(1) * len(py_ar)

112

In [90]:
np_ar.itemsize * np_ar.size

32